In [1]:
from numpy import genfromtxt, zeros
import numpy as np
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print data.shape
print target.shape
print set (target)

(150, 4)
(150,)
set(['setosa', 'versicolor', 'virginica'])


In [2]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [21]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t
, test_size=0.2, random_state=0)

In [31]:
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier
classifier1 = GradientBoostingClassifier().fit(data,t)
classifier2 = GradientBoostingClassifier().fit(train,t_train)

In [56]:
rate = np.arange(0.1, 1.1,0.1)
ne = np.arange(5,10,5)
gs=0.0
i=0
gscores = []
for r in rate:
    classifier1.set_params(learning_rate=r)
    classifier2.set_params(learning_rate=r)
    r1=r
    for n in ne:
        classifier1.set_params(n_estimators=n)
        classifier2.set_params(n_estimators=n)
        n1=n
        classifier1.fit(data,t)
        classifier2.fit(train,t_train)
        gs1=classifier1.score(data,t)
        gs2=classifier2.score(test,t_test)
        i=i+1
        if gs1>gs:
            gs=gs1
            print (i, r1, n1, gs1, gs2)

(1, 0.10000000000000001, 5, 1.0, 1.0)


In [62]:
classifier = GradientBoostingClassifier(n_estimators=5, learning_rate=1,max_depth=1, random_state=0).fit(data,t)

In [63]:
classifier.score(data,t)

0.97333333333333338

In [64]:
classifier.fit(train,t_train) 
print classifier.score(test,t_test)

1.0


In [65]:
from sklearn.metrics import confusion_matrix
print confusion_matrix(classifier.predict(test),t_test)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [66]:
from sklearn.metrics import classification_report
print classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica'])

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        11
 versicolor       1.00      1.00      1.00        13
  virginica       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

