In [1]:
from numpy import genfromtxt, zeros
import numpy as np
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print data.shape
print target.shape
print set (target)

(150, 4)
(150,)
set(['setosa', 'versicolor', 'virginica'])


In [2]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [4]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t
, test_size=0.4, random_state=0)

In [5]:
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier
classifier1 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(data,t)
classifier2 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(train,t_train)

In [6]:
rate = np.arange(0.1, 1.1,0.1)
ne = np.arange(5,200,5)
gs=0.0
i=0
gscores = []
for r in rate:
    classifier1.set_params(learning_rate=r)
    classifier2.set_params(learning_rate=r)
    r1=r
    for n in ne:
        classifier1.set_params(n_estimators=n)
        classifier2.set_params(n_estimators=n)
        n1=n
        classifier1.fit(data,t)
        classifier2.fit(train,t_train)
        gs1=classifier1.score(data,t)
        gs2=classifier2.score(test,t_test)
        i=i+1
        if gs1>gs:
            gs=gs1
            print (i, r1, n1, gs1, gs2)

(1, 0.10000000000000001, 5, 0.95333333333333337, 0.8833333333333333)
(3, 0.10000000000000001, 15, 0.96666666666666667, 0.8833333333333333)
(12, 0.10000000000000001, 60, 0.97333333333333338, 0.93333333333333335)
(17, 0.10000000000000001, 85, 0.97999999999999998, 0.94999999999999996)
(20, 0.10000000000000001, 100, 0.98666666666666669, 0.94999999999999996)
(22, 0.10000000000000001, 110, 0.99333333333333329, 0.94999999999999996)
(33, 0.10000000000000001, 165, 1.0, 0.94999999999999996)


In [7]:
classifier = GradientBoostingClassifier(n_estimators=165, learning_rate=0.1,max_depth=1, random_state=0).fit(data,t)

In [8]:
classifier.score(data,t)

1.0

In [9]:
classifier.fit(train,t_train) 
print classifier.score(test,t_test)

0.95


In [10]:
from sklearn.metrics import confusion_matrix
print confusion_matrix(classifier.predict(test),t_test)

[[16  0  0]
 [ 0 22  2]
 [ 0  1 19]]


In [11]:
from sklearn.metrics import classification_report
print classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica'])

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       0.96      0.92      0.94        24
  virginica       0.90      0.95      0.93        20

avg / total       0.95      0.95      0.95        60

