In [2]:
from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print data.shape
print target.shape
print set (target)

(150, 4)
(150,)
set(['setosa', 'versicolor', 'virginica'])


In [5]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [8]:
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier().fit(data,t)

In [9]:
classifier.score(data,t)

1.0

In [12]:
print t[0]
print t[1]
print t[2]
print t[3]

1.0
1.0
1.0
1.0


In [19]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t
, test_size=0.4, random_state=0)

In [20]:
classifier.fit(train,t_train) 
print classifier.score(test,t_test)

0.933333333333


In [21]:
from sklearn.metrics import confusion_matrix
print confusion_matrix(classifier.predict(test),t_test)

[[16  0  0]
 [ 0 23  4]
 [ 0  0 17]]


In [22]:
from sklearn.metrics import classification_report
print classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica'])

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       1.00      0.85      0.92        27
  virginica       0.81      1.00      0.89        17

avg / total       0.95      0.93      0.93        60

